config/routes.rb
Rails.application.routes.draw do
  
  
  root to: 'homes#top'
  get 'admin' => 'admin/homes#top'
  get '/homes/about' => 'homes#about', as: 'about'
  get 'searches/search'
  patch "content_reviews/:id/edit" => "content_reviews#update"
  
  
  # 顧客側の登録とログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  
  # 管理者側のログイン
  devise_for :admins, skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }
  
  resources :users, only: [:index, :show, :edit, :update]
  
  # content_reviewのidを取得する親子関係
  resources :content_reviews do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :index]
    resources :content_comments, only: [:create, :destroy]
  end
    
  namespace :admin do
    resources :content_reviews, only: [:index, :show, :edit, :create, :destroy]
    resources :content_comments, only: [:destroy]
  end
    
  
 
  
  
  
    
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/content_reviews_controller.rb
class Admin::ContentReviewsController < ApplicationController
  
    # 全ての投稿一覧（管理者側）
  def index
    # @content_reviews = ContentReview.all
    @content_reviews = ContentReview.page(params[:page])
  end

    # 各ユーザーの投稿一覧（管理者側）
  def show
    @content_review = ContentReview.find(params[:id])
  end

  # 投稿データの削除
  def destroy
    @content_review = ContentReview.find(params[:id])
    @content_review.destroy
    redirect_to admin_content_reviews_path    
  end
  
  
end

app/controllers/content_reviews_controller.rb
class ContentReviewsController < ApplicationController
  
  # 新規投稿のデータ
  def new
    @content_review = ContentReview.new
  end

  # 投稿データの保存
  def create
    @content_review = ContentReview.new(content_review_params)
    @content_review.user_id = current_user.id
    @content_review.score = params[:score]
    if @content_review.save
      flash[:notice] = "投稿が成功しました"
      redirect_to content_reviews_path
    else
      render :new
    end
  end


  # 投稿データ一覧表示
  def index
    # @content_reviews = ContentReview.all
    @content_reviews = ContentReview.page(params[:page])
  end

  # 投稿データの詳細ページとコメントの変数
  def show
    @content_review = ContentReview.find(params[:id])
    @content_comment = ContentComment.new
  end
  
  # 投稿データの編集ページ
  def edit
    @content_review = ContentReview.find(params[:id])
  end
  
  # 投稿データー更新機能
  def update
    @content_review = ContentReview.find(params[:id])
    @content_review.update(content_review_params)
    redirect_to content_review_path(@content_review)
  end
  
  
  
  # 投稿データの削除
  def destroy
    @content_review = ContentReview.find(params[:id])
    @content_review.destroy
    redirect_to content_reviews_path    
  end

  
  
  
  # 投稿データのストロングパラメータ
  private
  
  def content_review_params
    params.require(:content_review).permit(:get_root, :price, :explanation, :image, :title)
  end
  
  
end

app/helpers/admin/content_reviews_helper.rb
module Admin::ContentReviewsHelper
end

app/helpers/content_reviews_helper.rb
module ContentReviewsHelper
end

app/views/admin/content_reviews/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @content_review, url: edit_content_review_path(@content_review.id), method: :patch do |f| %>

  <!--投稿のデータの編集ページ-->
  <h4>タイトル</h4>
      <%= f.text_field :title %>
    <h4>画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4>入手ルート</h4>
      <%= f.text_field :get_root %>
    <h4>購入金額</h4>
      <%= f.text_field :price %>
    <h4>説明文</h4>
      <%= f.text_area :explanation %>
  <%= f.submit '保存' %>
  
<% end %>

app/views/admin/content_reviews/index.html.erb
<% @content_reviews.each do |content_review| %>
<div>
  <!--投稿の詳細ページに遷移-->
  <%#= link_to edit_admin_content_review_path(content_review.id) do %>
    <%= image_tag content_review.get_image %>
  <%# end %>

      
  <!--全ての投稿一覧-->
  <p>投稿ユーザー画像:<%= image_tag content_review.user.get_profile_image(100,100) %></p>
  
  <p>タイトル:<%= content_review.title %></p>
  <p>入手ルート:<%= content_review.get_root %></p>
  <p>購入金額:<%= content_review.price %></p>
  <p>説明文:<%= content_review.explanation %></p>
  <p>ユーザーネーム:<%= content_review.user.name %></p>
  <%= link_to "削除", admin_content_review_path(content_review), method: :delete %>
</div>
<% end %>

<!--ログインしているユーザーのみの投稿データ編集と削除機能-->
  <%# if @content_review.user != current_user %>
  <%# end %>
  
<%= paginate @content_reviews %>

app/views/admin/content_reviews/show.html.erb
<h1>管理者showページ</h1>
 
  <!--投稿の詳細内容-->
<div>
  <%= image_tag @content_review.get_image %>
  <p>投稿ユーザー画像：<%= image_tag @content_review.user.get_profile_image(100,100) %></p>
  <p>タイトル：<%= @content_review.title %></p>
  <p>入手ルート：<%= @content_review.get_root %></p>
  <p>購入金額：<%= @content_review.price %></p>
  <p>説明分：<%= @content_review.explanation %></p>
  <p>ユーザーネーム：<%= @content_review.user.name %></p>
  <p>投稿日時：<%= @content_review.created_at.strftime('%Y/%m/%d') %></p>
  
  <!--コメント投稿とコメント数の表示-->
<div>
  <p>コメント件数:<%= @content_review.content_comments.count %></p>
  <% @content_review.content_comments.each do |content_comment| %>
    <p><%= image_tag content_comment.user.get_profile_image(100,100) %></p>
    <%= content_comment.user.name %>
    <%= content_comment.created_at.strftime('%Y/%m/%d') %><%= content_comment.comment %>
    <%# if content_comment.user == current_user %>
      <%= link_to "削除", admin_content_comment_path(content_comment.id), method: :delete %>
    <%# end %>
  <% end %>
</div>