config/routes.rb
Rails.application.routes.draw do
  
  
  root to: 'homes#top'
  get 'admin' => 'admin/homes#top'
  get '/homes/about' => 'homes#about', as: 'about'
  get 'searches/search'
  patch "content_reviews/:id/edit" => "content_reviews#update"
  
  
  # 顧客側の登録とログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  
  # 管理者側のログイン
  devise_for :admins, skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }
  
  resources :users, only: [:index, :show, :edit, :update]
  
  # content_reviewのidを取得する親子関係
  resources :content_reviews do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :index]
    resources :content_comments, only: [:create, :destroy]
  end
    
  namespace :admin do
    resources :content_reviews, only: [:index, :show, :edit, :create, :destroy]
    resources :content_comments, only: [:destroy]
  end
    
  
 
  
  
  
    
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/content_reviews_controller.rb
class Admin::ContentReviewsController < ApplicationController
  
    # 全ての投稿一覧（管理者側）
  def index
    # @content_reviews = ContentReview.all
    @content_reviews = ContentReview.page(params[:page])
  end

    # 各ユーザーの投稿一覧（管理者側）
  def show
    @content_review = ContentReview.find(params[:id])
  end

  # 投稿データの削除
  def destroy
    @content_review = ContentReview.find(params[:id])
    @content_review.destroy
    redirect_to admin_content_reviews_path    
  end
  
  
end

app/controllers/content_reviews_controller.rb
class ContentReviewsController < ApplicationController
  
  # 新規投稿のデータ
  def new
    @content_review = ContentReview.new
  end

  # 投稿データの保存
  def create
    @content_review = ContentReview.new(content_review_params)
    @content_review.user_id = current_user.id
    @content_review.score = params[:score]
    if @content_review.save
      flash[:notice] = "投稿が成功しました"
      redirect_to content_reviews_path
    else
      render :new
    end
  end


  # 投稿データ一覧表示
  def index
    # @content_reviews = ContentReview.all
    @content_reviews = ContentReview.page(params[:page])
  end

  # 投稿データの詳細ページとコメントの変数
  def show
    @content_review = ContentReview.find(params[:id])
    @content_comment = ContentComment.new
  end
  
  # 投稿データの編集ページ
  def edit
    @content_review = ContentReview.find(params[:id])
  end
  
  # 投稿データー更新機能
  def update
    @content_review = ContentReview.find(params[:id])
    @content_review.update(content_review_params)
    redirect_to content_review_path(@content_review)
  end
  
  
  
  # 投稿データの削除
  def destroy
    @content_review = ContentReview.find(params[:id])
    @content_review.destroy
    redirect_to content_reviews_path    
  end

  
  
  
  # 投稿データのストロングパラメータ
  private
  
  def content_review_params
    params.require(:content_review).permit(:get_root, :price, :explanation, :image, :title)
  end
  
  
end

app/helpers/admin/content_reviews_helper.rb
module Admin::ContentReviewsHelper
end

app/helpers/content_reviews_helper.rb
module ContentReviewsHelper
end

app/views/content_reviews/_list.html.erb
<% content_reviews.each do |content_review| %>
  
<div>
  <!--投稿の詳細ページに遷移-->
  <%= link_to content_review_path(content_review.id) do %>
    <%= image_tag content_review.get_image, size: "200x200" %>
  <% end %>

      
  <!--全ての投稿一覧-->
  <% if user_signed_in? %>
  <!--<p>投稿ユーザー画像:<%#= image_tag content_review.user.get_profile_image(100,100) %></p>-->
  <p>タイトル:<%= content_review.title %></p>
  <p>入手ルート:<%= content_review.get_root %></p>
  <p>購入金額:<%= content_review.price %></p>
  <p>説明文:<%= content_review.explanation %></p>
  <p>ユーザーネーム:<%= content_review.user.name %></p>
  <%= render 'content_reviews/static_rate', content_review: content_review %>
  <p><%= link_to "#{content_review.content_comments.count} コメント", content_review_path(content_review.id) %></p>
</div>
  <% elsif admin_signed_in? %>
  <p>投稿ユーザー画像:<%= image_tag content_review.user.get_profile_image(100,100) %></p>
  <p>タイトル:<%= content_review.title %></p>
  <p>入手ルート:<%= content_review.get_root %></p>
  <p>購入金額:<%= content_review.price %></p>
  <p>説明文:<%= content_review.explanation %></p>
  <p>ユーザーネーム:<%= content_review.user.name %></p>
  <%= link_to "コメントを確認", admin_content_review_path(content_review.id) %>
  <% end %>


<% end %>

  

app/views/content_reviews/_static_rate.html.erb
<div id="rate_<%= content_review.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
    let raty_<%= content_review.id %> = document.querySelector('#rate_<%= content_review.id %>');
    rate_<%= content_review.id %>.innerHTML = ""
    let option_<%= content_review.id %> = {  
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        score: "<%= content_review.score %>",
        readOnly: true,
      };
    raty(raty_<%= content_review.id %> ,option_<%= content_review.id %>);
});
</script>

app/views/content_reviews/index.html.erb
<!--フラッシュメッセージ（新規投稿）-->
<div><%= flash[:notice] %></div>


      <!--ユーザーの投稿一覧-->
      <%= render 'list', content_reviews: @content_reviews %>

      <%= paginate @content_reviews %>
      </div>
    </div>
  </div>
</div>

app/views/content_reviews/new.html.erb
<h1>レビューフォーム</h1>
  
  <!--バリデーションのエラーメッセージ表示-->
  <% if @content_review.errors.any? %>
  <%= @content_review.errors.count %>点の記入漏れがあります
  <ul>
    <% @content_review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  
  
  <!--新規投稿するフォーム-->
  <%= form_with model: @content_review do |f| %>
    <div class="col-xs-6">
      <div class="form-group">
      <table class="table table-bordered table-hover">
        <tr>
          <th><%= f.label :タイトル%></th>
          <th><%= f.text_field :title %></th>
      </div>
        </tr>
        
        <tr>
        <div class="form-group">
          <th><%= f.label :画像 %></th>
          <th><%= f.file_field :image, accept: "image/*" %></th>
        </div>
        </tr>
        
        <tr>
        <div class="form-group">
          <th><%= f.label :入手ルート %></th>
          <th><%= f.text_field :get_root %></th>
        </div>
        </tr>
        
        <tr>
        <div class="form-group">
          <th><%= f.label :購入金額 %></th>
          <th><%= f.text_field :price %></th>
        </div>
        </tr>
        
        <tr>
        <div class="form-group">
          <th><%= f.label :説明文 %></th>
          <th><%= f.text_area :explanation %>
            <div class="row ml-1">
              <p>評価:</P>
                <div class="col-md-3 position-static">
                  <div id="post_raty"></div>
                </div>
              <script>
                var elem = document.getElementById('post_raty');
                var opt = {  
                starOn: "<%= asset_path('star-on.png') %>",
                starOff: "<%= asset_path('star-off.png') %>",
                starHalf: "<%= asset_path('star-half.png') %>",
                };
                raty(elem,opt);
              </script>
            </div>
        
    <%= f.submit '投稿' %>
  <% end %>
          </th>
        </tr>
      </table>
    </div>

app/views/content_reviews/show.html.erb
<!--フラッシュメッセージ（コメント投稿）-->
<div><%= flash[:notice] %></div>

  <!--投稿の詳細内容-->
<div>
  <%= image_tag @content_review.get_image %>
  <p>投稿ユーザー画像：<%= image_tag @content_review.user.get_profile_image(100,100) %></p>
  <p>タイトル：<%= @content_review.title %></p>
  <p>入手ルート：<%= @content_review.get_root %></p>
  <p>購入金額：<%= @content_review.price %></p>
  <p>説明分：<%= @content_review.explanation %></p>
  <p>ユーザーネーム：<%= @content_review.user.name %></p>
  <p>投稿日時：<%= @content_review.created_at.strftime('%Y/%m/%d') %></p>
  
    <!--ログインしているユーザーのみの投稿データ編集と削除機能-->
  <% if @content_review.user == current_user %>
    <%= link_to "編集", edit_content_review_path(@content_review) %>
    <%= link_to "削除", content_review_path(@content_review), method: :delete %>
  <% end %>

  <!--いいね機能で「含まれる時/含まれない時」の表示と機能-->
  <% if @content_review.favorited_by?(current_user) %>
    <p>
      <%= link_to content_review_favorites_path(@content_review), method: :delete do %>
        ♥<%= @content_review.favorites.count %> いいね
      <% end %>    
    </p>
    <% else %>
    <p>
       <%= link_to content_review_favorites_path(@content_review), method: :post do %>
        ♡<%= @content_review.favorites.count %> いいね
        <% end %>
    </p>
  <% end %>
</div>

<!--コメント投稿とコメント数の表示-->
<div>
  <p>コメント件数:<%= @content_review.content_comments.count %></p>
  <% @content_review.content_comments.each do |content_comment| %>
    <p><%= image_tag content_comment.user.get_profile_image(100,100) %></p>
    <%= content_comment.user.name %>
    <%= content_comment.created_at.strftime('%Y/%m/%d') %><%= content_comment.comment %>
    <% if content_comment.user == current_user %>
      <%= link_to "削除", content_review_content_comment_path(content_comment.content_review, content_comment), method: :delete %>
    <% end %>
  <% end %>
</div>

<div>
  <%= form_with model: [@content_review, @content_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>