config/routes.rb
Rails.application.routes.draw do
  
  
  root to: 'homes#top'
  get 'admin' => 'admin/homes#top'
  get '/homes/about' => 'homes#about', as: 'about'
  get 'searches/search'
  patch "content_reviews/:id/edit" => "content_reviews#update"
  
  
  # 顧客側の登録とログイン
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  
  # 管理者側のログイン
  devise_for :admins, skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }
  
  resources :users, only: [:index, :show, :edit, :update]
  
  # content_reviewのidを取得する親子関係
  resources :content_reviews do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create, :index]
    resources :content_comments, only: [:create, :destroy]
  end
    
  namespace :admin do
    resources :content_reviews, only: [:index, :show, :edit, :create, :destroy]
    resources :content_comments, only: [:destroy]
  end
    
  
 
  
  
  
    
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content_comment.rb
class ContentComment < ApplicationRecord

  # userとcontent_reviewに属するアソシエーション（コメント機能）
  belongs_to :user
  belongs_to :content_review

end

app/models/content_review.rb
class ContentReview < ApplicationRecord
 
  # ActiveStorageを使って画像を持たせるため（投稿画像）
  has_one_attached :image

  # userに属するアソシエーション
  belongs_to :user
  
  # アソシエーションでたくさん持っている側（コメント機能といいね機能とレビュー機能）
  has_many :content_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # バリデーションの設定
  validates :title, presence:true
  validates :image, presence:true
  validates :get_root, presence: true
  validates :price, presence: true
  validates :explanation, presence: true

  # ユーザidがfavoritesテーブルに存在するか調べる（trueかfalse）
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # ５段階星レビューの機能
  def self.search_for(content, method)
    if method == 'perfect'
      ContentReview.where(title: content)
    elsif method == 'forward'
      ContentReview.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      ContentReview.where('title LIKE ?', '%'+content)
    else
      ContentReview.where('title LIKE ?', '%'+content+'%')
    end
  end
  
  # デフォルトの画像設定
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end


end

app/models/favorite.rb
class Favorite < ApplicationRecord

  # userとcontent_reviewに属するアソシエーション（いいね機能）
  belongs_to :user
  belongs_to :content_review  

end

app/models/review.rb
class Review < ApplicationRecord
  
  # userとcontent_reviewに属するアソシエーション（レビュー機能）
  belongs_to :user
  belongs_to :content_review
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーションでたくさん持っている側（投稿とコメント機能といいね機能とレビュー機能）
  has_many :content_reviews, dependent: :destroy
  has_many :content_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # ActiveStorageを使って画像を持たせるため(プロフィール画像）
  has_one_attached :profile_image

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end



  # メソッドに引数設定し、設定した値に画像サイズの変換をする
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  # いいね機能の記述
  def create
    content_review = ContentReview.find(params[:content_review_id])
    favorite = current_user.favorites.new(content_review_id: content_review.id)
    favorite.save
    redirect_to content_review_path(content_review)
  end

  # いいねを解除する記述
  def destroy
    content_review = ContentReview.find(params[:content_review_id])
    favorite = current_user.favorites.find_by(content_review_id: content_review.id)
    favorite.destroy
    redirect_to content_review_path(content_review)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :authenticate_user!, except: [:top]

  def top
  end

  def about
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
    
  def create
    @review = Review.new(review_params)
  end

  private
  def review_params
    params.permit(:content_review_id, :score, :content)
  end  
  

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def search
      @model = params[:model]
      @content = params[:content]
      @method = params[:method]
      if @model == 'user'
        @records = User.search_for(@content,@method)
      else
        @records = ContentReview.search_for(@content,@method)
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, only: [:show]
  
  def index
  end

  # ユーザー詳細ページ
  def show
    @user = User.find(params[:id])
    @content_reviews = @user.content_reviews.page(params[:page])
  end

  # ユーザー編集ページ
  def edit
    @user = User.find(params[:id])
  end
  
  # ユーザー情報の更新機能
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "ユーザー情報を更新しました"
    redirect_to user_path(@user)
  end

  
  # ユーザー情報の更新ストロンパラメータ
  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_comments_helper.rb
module ContentCommentsHelper
end

app/helpers/content_reviews_helper.rb
module ContentReviewsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_search.html.erb
<div class="serch_form">
    <%= form_with url: searches_search_path,method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model,options_for_select({"ユーザー"=>"user","レビュー"=>"content_review"})%>
    <%= f.select :method,options_for_select({"完全一致"=>"perfect","前方一致"=>"forward",
        "後方一致"=>"backward","部分一致"=>"partial"})%>
    <%= f.submit'検索' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarTips</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6048dcdb5a.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
    
    <!--ユーザーでログインしている時-->
    <% if user_signed_in? %>
      <li>
      <%= link_to '投稿', new_content_review_path %>
      </li>
       <li>
      <%= link_to '投稿一覧', content_reviews_path %>
      </li>
      <li>
      <%= link_to 'マイページ', user_path(current_user.id) %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li><br>
      <%= render 'layouts/search' %></br>
      
      <!--adminでログインしている時-->
    <% elsif admin_signed_in? %>
      <li>
      <%= link_to '投稿一覧', admin_content_reviews_path %>
      </li>
      <li>
      <%= link_to 'ユーザー一覧', admin_path %>
      </li>
      <li>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
      </li>
      
    <% else %>
      <!--ログインしていない時-->
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
      <li>
      <%= link_to '投稿', new_content_review_path %>
      </li>
      <li>
      <%= link_to '投稿一覧', content_reviews_path %>
      </li>
    <% end %>
  </header>
  
    <!--<%# if flash[:notice] %>-->
    <!--  <div class="notification is-info">-->
    <!--    <p class="notice"><%#= notice %></p>-->
    <!--  </div>-->
    <!--<%# end %>-->
    <!--<%# if flash[:alert] %>-->
    <!--  <div class="notification is-danger">-->
    <!--    <p class="alert"><%#= alert %></p>-->
    <!--  </div>-->
    <!--<%# end %>-->
  
  
    <%= yield %>
  </body>
</html>